### ISSUE TITLE
More testing idea

### ISSUE THREAD

**Issue by wusatosi** [bemanproject/dump#2]
I think we need some kind of test that verifies that the `dump()` call is implemented correctly. One way this could be done is to:

1. Write a short CMake script that runs a program that calls `dump()`, pipes it to a file, and verifies its output
2. Register the CMake execution as a test using `add_test`

_Originally posted by @camio in https://github.com/beman-project/dump/pull/1#discussion_r1769327409_

**Comment by neatudarius** [comment]
No need for work here. Will deprecate this library.
